/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "PB_N8raAIb4",
    title: "Monica and Chandler | Their Story",
    thumbnail: "https://img.youtube.com/vi/PB_N8raAIb4/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=PB_N8raAIb4",
    playtime: "5:18",
    author: "HBO Max",
    authorImg:
      "https://yt3.ggpht.com/TcXFMFkDeUN8pDqZ-2WShXiG6lXtpoRG2kfRMg3Nd9g947mESyRYqlWtwcoy9FyjiiLVLaTd=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Sep 20, 2021",
    views: 165_658,
  },
  {
    _id: "NHhKX1ZMHYc",
    title: "Nagisa God mode",
    thumbnail: "https://img.youtube.com/vi/NHhKX1ZMHYc/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=NHhKX1ZMHYc&ab_channel=AizenSousuke",
    playtime: "1:50",
    author: "Aizen Susuke",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSNzWodXTf7M6_KNB9XgTtVWzNg2TwI81TlKeUH=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Jul 10, 2020",
    views: 213_239,
  },
  {
    _id: "lnbQGTQ1mw8",
    title: "Naruto Vs Pain AMV -[Skillet] Hero/Monster HD",
    thumbnail: "https://img.youtube.com/vi/lnbQGTQ1mw8/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=lnbQGTQ1mw8&ab_channel=D-Deca",
    playtime: "6:08",
    author: "D- Deca",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLTvkfDR5z6Ttn1uRb7j89XsVc6gRE-rrL9WCUar=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Aug 13, 2015",
    views: 6_231_509,
  },
  {
    _id: "OSyKhqDsW14",
    title: "Goku Vs. Jiren「AMV」- Get Me Out",
    thumbnail: "https://img.youtube.com/vi/OSyKhqDsW14/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=OSyKhqDsW14&ab_channel=ReinelexMusic",
    playtime: "3:43",
    author: "Reinelex Music",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRDGX6t7z1kcwerj8DLaplx0xTbuDvIXmXbKBz13A=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Oct 8, 2017",
    views: 5_478_12,
  },
  {
    _id: "QTwRrg0bJ8I",
    title: "[AMV」Dragon Ball Super: Centuries",
    thumbnail: "https://img.youtube.com/vi/QTwRrg0bJ8I/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=QTwRrg0bJ8I&ab_channel=SanjinoKanta",
    playtime: "3:48",
    author: "Sanjino Kanta",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRc4ff0eFCrjsvCcJt7AdzwYl9mGbVTDQkt3qJXVQ=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Mar 4, 2018",
    views: 7_555_662,
  },
  {
    _id: "XbhecuoEgxs",
    title: "Kung Fu Panda | Who Are You",
    thumbnail: "https://img.youtube.com/vi/XbhecuoEgxs/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=XbhecuoEgxs&ab_channel=KhaledOsman",
    playtime: "6:04",
    author: "Khaled Osman",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSWPTePakGs-gnsKO0eDgshcv8O6JnHJ-89-G7Z=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Jan 3, 2021",
    views: 7_555_662,
  },
  {
    _id: "km2OPUctni4",
    title: "Saitama vs Genos Fight | One Punch Man (60FPS)",
    thumbnail: "https://img.youtube.com/vi/km2OPUctni4/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=km2OPUctni4&ab_channel=60FpsStation",
    playtime: "3:55",
    author: "60FpsStation",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSWPTePakGs-gnsKO0eDgshcv8O6JnHJ-89-G7Z=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Oct 19, 2016",
    views: 28_381_303,
  },
  {
    _id: "ZzuFVbVHfYY",
    title: "Code Geass Top 6 Lelouch Epic Moments",
    thumbnail: "https://img.youtube.com/vi/ZzuFVbVHfYY/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=ZzuFVbVHfYY&ab_channel=AnimeClub2020",
    playtime: "6:04",
    author: "AnimeClub2020",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLRvjZXZ1qpZmdUi_hX_llUoJhLOf6vNWBoy-mza=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Sep 18, 2020",
    views: 7_568_452,
  },
  {
    _id: "11fJ18huVSg",
    title: "DBS - Goku's little surprise to other God's",
    thumbnail: "https://img.youtube.com/vi/11fJ18huVSg/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=11fJ18huVSg&ab_channel=GBG",
    playtime: "2:32",
    author: "GBG",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSJCpLUOWSXEfOBhyGnmYCp8h7gEseLhZNw8F-xRA=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Mar 6, 2017",
    views: 3_446_556,
  },
  {
    _id: "NlJZ-YgAt-c",
    title: "Death Note | OFFICIAL TRAILER",
    thumbnail: "https://img.youtube.com/vi/NlJZ-YgAt-c/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=NlJZ-YgAt-c&ab_channel=CrunchyrollCollection",
    playtime: "1:51",
    author: "CrunchyrollCollection",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSJCpLUOWSXEfOBhyGnmYCp8h7gEseLhZNw8F-xRA=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Dec 16, 2019",
    views: 1_265_75,
  },
  {
    _id: "1ruo0arhFMw",
    title: "Death Note: The Best Moments",
    thumbnail: "https://img.youtube.com/vi/1ruo0arhFMw/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=1ruo0arhFMw&ab_channel=karlyharris",
    playtime: "2:32",
    author: "GBG",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLSK-cBDAINpKsRmYdpsd63koMzEob4Z38VDxZzmyQ=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Mar 6, 2017",
    views: 5_054_256,
  },
  {
    _id: "TByW5-HDYTA",
    title: "One Punch Man (Season 1) - Episode 05 [English Sub]",
    thumbnail: "https://img.youtube.com/vi/TByW5-HDYTA/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=TByW5-HDYTA&ab_channel=MuseAsia",
    playtime: "24:29",
    author: "MuseAsia",
    authorImg:
      "https://yt3.ggpht.com/xdgNgosFHeVJ8BNdypwReOje1Luer4O521yV1-k5lVWRuRdmHzq9kLsNz9eVLRBCewW56fP9CQ=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Feb 28, 2022",
    views: 15_318_230,
  },
  {
    _id: "2iRqm4CFSmc",
    title: "Saitama vs Suiryu",
    thumbnail: "https://img.youtube.com/vi/2iRqm4CFSmc/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=2iRqm4CFSmc&ab_channel=SuperSaitama",
    playtime: "3:08",
    author: "SuperSaitama",
    authorImg:
      "https://yt3.ggpht.com/xdgNgosFHeVJ8BNdypwReOje1Luer4O521yV1-k5lVWRuRdmHzq9kLsNz9eVLRBCewW56fP9CQ=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Apr 19, 2021",
    views: 7_190_567,
  },
  {
    _id: "g09B-Brv7Vs",
    title: "Saitama gets mad at being bothered by B rank guys ",
    thumbnail: "https://img.youtube.com/vi/g09B-Brv7Vs/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=g09B-Brv7Vs&ab_channel=TheOgre",
    playtime: "5:30",
    author: "The Ogre",
    authorImg:
      "https://yt3.ggpht.com/xdgNgosFHeVJ8BNdypwReOje1Luer4O521yV1-k5lVWRuRdmHzq9kLsNz9eVLRBCewW56fP9CQ=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Sep 20, 2021",
    views: 5_545_127,
  },
  {
    _id: "kvTHEAnk_wk",
    title: "Tokyo Ghoul - Unravel AMV",
    thumbnail: "https://img.youtube.com/vi/kvTHEAnk_wk/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=kvTHEAnk_wk&ab_channel=LuceroGAMER096",
    playtime: "3:48",
    author: "LuceroGAMER096",
    authorImg:
      "https://yt3.ggpht.com/xdgNgosFHeVJ8BNdypwReOje1Luer4O521yV1-k5lVWRuRdmHzq9kLsNz9eVLRBCewW56fP9CQ=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Aug 20, 2018",
    views: 519,
  },
  {
    _id: "XHViAiVuDsA",
    title: "Code Geass - Continued Story",
    thumbnail: "https://img.youtube.com/vi/XHViAiVuDsA/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=XHViAiVuDsA&ab_channel=Lu5ck",
    playtime: "5:13",
    author: "Lu5ck",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLR-BZT28k8oSeh1lfr4FagUJncKVNWK9kXZ0YI3=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Oct 1, 2008",
    views: 6_462_192,
  },
  {
    _id: "WaUhYg7mfl0",
    title: "Nagisa: Assassin Mode",
    thumbnail: "https://img.youtube.com/vi/WaUhYg7mfl0/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=WaUhYg7mfl0&ab_channel=EbelleLimbaga",
    playtime: "6:02",
    author: "Ebelle Limbaga",
    authorImg:
      "https://yt3.ggpht.com/LEbe8wH1b0T4RFh2HKZBETTWFEGv713vy9wBzKqZIlQLGrUiK6VJ4yUu0o2fOMI34Ac-9gc4bw=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Apr 24, 2021",
    views: 6_462_192,
  },
  {
    _id: "fqt6xBtyDs4",
    title: "One Punch Man (Season 2) - Episode 18 [English Sub]",
    thumbnail: "https://img.youtube.com/vi/fqt6xBtyDs4/hqdefault.jpg",
    src: "https://www.youtube.com/watch?v=fqt6xBtyDs4&ab_channel=MuseAsia",
    playtime: "23:50",
    author: "Muse Asia",
    authorImg:
      "https://yt3.ggpht.com/ytc/AKedOLR-BZT28k8oSeh1lfr4FagUJncKVNWK9kXZ0YI3=s88-c-k-c0x00ffffff-no-rj",
    dateUploaded: "Oct 31, 2020",
    views: 4_535_586,
  },
];
